### ISSUE TITLE
Failed JUnit Test

### ISSUE THREAD

**Issue by SquidDaK1D** [jody/helloCS3250#19]
A JUnit test fails because there is not a null parameter version of the method.

**Comment by jody** [comment]
I don't understand the rationale for the implied assertion that there should be _multiple versions_ of the method.
That seems like it would only be required for different method signatures, not different values of a parameter.

**Comment by jody** [comment]
Duplicate of #24

**Comment by SquidDaK1D** [comment]
Now that I re-read my comment I realize that it was vague and didn't use technical terms. I think your suggestion of different method signatures is what I was thinking of when I said referred to a different version, I just didn't express what I meant well at all.

**Comment by jody** [comment]
No worries.

(In practice, the null case is still part of the one-parameter version of the method, with `null` being passed as the parameter.)
