### ISSUE TITLE
Junit Tests sayHelloEmptyStringTest and sayHelloNullTest fail

### ISSUE THREAD

**Issue by chrisreylo73** [jody/helloCS3250#21]
Test sayHelloEmptyStringTest expects "Hello" but produces "Hello ".
Test sayHelloNullTest expects "Hello!" but produces "Hello null"

**Comment by jody** [comment]
Unless these are two instances of the same shortcoming, this needs to be broken into two separate issues.

**Comment by chrisreylo73** [comment]
I am going to separate the issues.

**Comment by jody** [comment]
I also note that Issue #13 appears to previously have identified the sayHelloEmptyStringTest concern and is already in the project To Do lane.  Marking this as a duplicate (even though a part of it is new).
