### ISSUE TITLE
Checkstyle Errors on file HelloAnyonetest.java

### ISSUE THREAD

**Issue by am10nxw** [jody/helloCS3250#38]
There are checkstyle errors on the HelloAnyontest.java file.

Errors:
Unused import - org.junit.jupiter.api.Test.
Comment matches to-do format 'TODO:'.

**Comment by jody** [comment]
Please update to use the correct name of the file.

It is useful to include an internal link to the source code file as another way of making sure that the correct file is identified.

**Comment by jody** [comment]
No response.
