### ISSUE TITLE
Trailing space error

### ISSUE THREAD

**Issue by bishnu19** [jody/helloCS3250#49]
checkstyle report shows trailing space error on line 34 on HelloAnyone.java
Here is the link for the file:
https://github.com/jody/helloCS3250/blob/master/src/metrocs/HelloAnyone.java

> Please add information about the file or files affected in the title. It is also helpful to link to put a link the line of the affected file using GitHub markdown.

**Comment by jody** [comment]
Please add information about the file or files affected in the title. It is also helpful to link to put a link the line of the affected file using GitHub markdown.

**Comment by jody** [comment]
No response.
