### ISSUE TITLE
[User Story]HelloWorldTest problems and Redundancies

### ISSUE THREAD

**Issue by millerac38** [jody/helloCS3250#68]
-The unnecessaryTest on line 35 is redundant since the object is never null, create a more complex test to fully ensure code is working properly.
-Getting run problems such as, "Cannot resolve symbol"  etc.

**Comment by jody** [comment]
> --Getting run problems such as, "Cannot resolve symbol" etc.

Insufficient information to know what this means or its relevance to the previous statement in this issue. Please consider rewriting as a "User Story".
