### ISSUE TITLE
Java 14 or higher not supported

### ISSUE THREAD

**Issue by NickLM1200** [jody/helloCS3250#69]
While running the program if the version of java is 14 or higher, the program won't run. A window with the legend "Java: error: release version 14 not supported" so for this project will be necessary to run a lower version of Java.

**Comment by millerac38** [comment]
I also noticed this issue, if anyone has problems with it on IntelliJ go to:  "File -> Settings ->Compiler -> Java Compiler -> 'Project bytecode version:' " I selected 10 and it worked in case anyone needs help.
