### ISSUE TITLE
Refactor HelloWorld.java and HelloAnyone.java

### ISSUE THREAD

**Issue by BatchOfAllTrades** [jody/helloCS3250#70]
Objective:
Refactor the [HelloWorld.java](https://github.com/jody/helloCS3250/blob/master/src/metrocs/HelloWorld.java) and [HelloAnyone.java](https://github.com/jody/helloCS3250/blob/master/src/metrocs/HelloAnyone.java) to facilitate future changes that would allow for strings other than "world" to be passed to the toWhom argument of the sayHello method.

Background:
The current call to the sayHello method uses a hard-coded string.  A variable would allow for different strings to be passed to the method without changing the individual function calls.  This would improve continuity in the code.  See issue #30 
 
Suggested Approach:
Refactor so that a single common stem is used, modified as necessary to reflect the parameter value.

References:
https://www.refactoring.com

**Comment by jody** [comment]
No verification/acceptance criteria. This seems too vague.
